### ISSUE TITLE
drawEllipse3d: How to define the orientation of the ellipse in the 3d plane?

### ISSUE THREAD

**Issue by oqilipo** [mattools/matGeom#10]
Hello

I would like to use: drawEllipse3d

Can you explain how to define the orientation of the ellipse in the plane, that is defined by THETA & PHI?
In other words, the rotation around the normal of the plane?

Thanks in advance

**Comment by dlegland** [comment]
Hi,

The rotation in the supporting plane of the ellipse (ie, around the normal) is specified by a third angle called PSI. 

The transformation from a point on the ellipse to the 3D point is given by the succession of transforms:
* initialize x = R1 * cos(t) and y = R2 * sin(t) (standard ellipse parameterization), and set z = 0.
* apply a rotation by PSI around the Z axis 
* apply a rotation by THETA around the Y axis
* apply a rotation by PHI around the Z axis
* apply a 3D translation to replace the ellipse around its center

Hope this helps !

**Comment by oqilipo** [comment]
Thanks, that helped me.

But another problem arose.

Is there an unambiguous way to extract PSI, THETA, PHI from a 3x3 rotation matrix?
I've used:
angles3d3 = rad2deg(rotm2eul(R','ZYZ'));
THETA = -angles3d3(2);
PHI = -angles3d3(3);
PSI = angles3d3(1);
but in some case the correct solution is PSI and in the other it's 180°-PSI.

Thanks a lot.

**Comment by dlegland** [comment]
Hi,
From what I remember, it is difficult to keep a perfect one-to-one mapping between euler angles and rotation matrix. Moreover, I could not find clear consensus on conventions for angle order or sign...

Two hints:
* if theta is larger than 180 degrees, this could cause ambiguities. By digging into files, it seems I used theta within [0 180] degrees as convention.
* It is not always clear which of PSI or PHI is applied first. Sometimes swapping them makes things better...

The code can be found in "geom3d/private/localToGlobal3d".

regards,
