### ISSUE TITLE
Why include rad2deg and deg2rad in matGeom?

### ISSUE THREAD

**Issue by oqilipo** [mattools/matGeom#100]
These functions are build-in MATLAB functions:

https://se.mathworks.com/help/matlab/ref/rad2deg.html
https://se.mathworks.com/help/matlab/ref/deg2rad.html

?

**Comment by dlegland** [comment]
Hi,
for historical reasons actually: I was needing them before they were introduced in 2015...
But it's 5 years ago, I will put them in obsolete directory soon!

**Comment by oqilipo** [comment]
That makes sense ;-)

However, why not deleting them instead of moving them to the deprecated folder?
That would avoid the name conflict. The code is still archived in the git log.

**Comment by dlegland** [comment]
yes, better... I just pushed the related commit (https://github.com/mattools/matGeom/commit/b8ce46e8892e0629d34623163d8170dde32b1aa3)
