### ISSUE TITLE
Add option to rotation3dToEulerAngles to check if rotation matrix contains scaling or reflection?

### ISSUE THREAD

**Issue by oqilipo** [mattools/matGeom#102]
Hi  David

I was thinking about implementing an option to check in rotation3dToEulerAngles if the rotation matrix contains scaling or reflection (see: [isTransform3d(TFM, 'rotation', 1)](https://github.com/mattools/matGeom/blob/master/matGeom/geom3d/isTransform3d.m))

What do you think? Should this check by default be true and throw an error or warning?
IMO it should be true since the reconversion from the euler angles to the rotation matrix won't produce the same input rotation matrix. 
How would you call the parameter: 'ScalingReflection', 'RotationOnly', 'PureRotation'?

If it does not make sense at all to calculate euler angles if the matrix contains scaling or reflection we simply could add the following line to rotation3dToEulerAngles:
addRequired(p, 'mat', @(x) isTransform3d(x, 'rotation', true));

Kind regards

**Comment by dlegland** [comment]
Hi,

I'm mitigated... 
One problem is that one need to take care about rounding effect, and have some tolerance on the test.
Also it is the responsability of the programmer who call the function to ensure the call is valid.

Throwing a warning instead of an error sounds better to me.

**Comment by oqilipo** [comment]
Ok, then I would add two parameter pairs in rotation3dToEulerAngles:
'IsRotation' - true by default: checks if it is pure rotation and throws a warning if not. If set to false, the test is omited.
'Tolerance' - what default value would you propose? eps*1e8 is used at the moment in isTransform3d. Should maybe depend on the class?

Kind regards

**Comment by dlegland** [comment]
yes, looks fine!
for the tolerance, I used to use a fixed value, usually 1e-8 or 1e-10. eps * 1e8 is fine as well.

**Comment by oqilipo** [comment]
Done in 
240e9b4
