### ISSUE TITLE
Intersection points with a polygon

### ISSUE THREAD

**Issue by raz1** [mattools/matGeom#107]
Hi, 

Why I can not get the intersection point of angles 0 and 270?  

Code:
```
clc;
clear all;
close all;
% draw angle lines
xCenter = 17;
yCenter = 8;
poly = polyshape([ 15 15 20 15 10],[ 10 0 10 15 0]);
plot(poly)
poly1 = poly.Vertices;
hold on;
L=10; %Line length, can be changed
angle = 90; %Choose angle, can be more
  
for langle =  0:angle:359 
    langle
    x2=xCenter+ L * cosd(langle);
    y2=yCenter+ L * sind(langle);    
    line([xCenter,x2], [yCenter,y2], 'Color', 'r', 'LineWidth', 1);
    text(x2,y2,string(langle));
    lineseg = [xCenter x2  yCenter y2];
    P = intersectLinePolygon(lineseg, poly1) %https://www.mathworks.com/matlabcentral/mlc-downloads/downloads/submissions/7844/versions/27/previews/geom2d/polygons2d/intersectLinePolygon.m/index.html
    pause(1);
end
```

Thanks,
Elyraz

**Comment by dlegland** [comment]
Hi Elyraz,

First of all thank you for your detailed bug report, this greatly helps identifying problems!

Actually the problem relies on the definition of line. In geom2d/MatGeom, I defined "line" as straight line, passing through an origin, and with a slope given by a vector. For linear objects defined by two extremities, I used the term "edge", with representation given by [x1 y1  x2 y2].

Therefore, you should obtain expected result by replacing the last lines within the loop by the following ones:

    lineseg = [xCenter yCenter x2  y2];
    P = intersectEdgePolygon(lineseg, poly1) %https://www.mathworks.com/matlabcentral/mlc-downloads/downloads/submissions/7844/versions/27/previews/geom2d/polygons2d/intersectLinePolygon.m/index.html

Hope this helps?
Best,
David

**Comment by raz1** [comment]
Thanks for the fast reply.
