### ISSUE TITLE
wrong result in expandPolygon

### ISSUE THREAD

**Issue by JR9124** [mattools/matGeom#111]
Thanks for the toolbox, there is an wrong result when I use expandPolygon, the data of the polygon to be expanded is as follows, could you fix the problem? Thanks. 
853.051180799598	1395.70358899983
846.846474586138	1395.32617807027
846.951002029201	1389.16946937456
847.049465466440	1383.00346819798
847.115303592170	1376.85448205073
847.212947131441	1370.65928019451
847.311508545437	1364.45976668292
847.403016456476	1358.24915772477
847.490919675847	1352.26606379952
847.584953624545	1346.07363613856
847.666275665442	1339.82100248509
839.484169584245	1331.11609184023
853.924979622264	1328.35348776418
861.608595085196	1330.39278847797
868.220412668110	1329.50225988558
875.875477336126	1326.86553173669
882.338554063435	1331.62175833310
889.962694098544	1329.23277737873
896.696359642413	1327.45790296303
903.937867677510	1326.07854037217
910.210804103418	1329.25401056939
917.917413331487	1327.91251671165
924.032548384970	1327.19436486693
932.054192215014	1325.47600388931
938.211349348105	1324.78402538707
945.488069284109	1327.43691050576
952.183413420216	1327.69255892283
959.337184914622	1323.21728444434
965.732226050554	1323.44919709893
972.831942294955	1326.13117367279
979.356603578110	1326.42560472448
979.301477969154	1332.27428590649
979.258237679396	1338.08098724113
979.227623462547	1344.09664403141
979.192051120088	1350.04053171916
979.148771060482	1356.00669735001
979.124731066183	1361.85792147696
979.097106343355	1367.81934911268
986.680635796704	1374.45102609546
986.654474782696	1380.53098978249
986.602625334353	1386.65544435229
978.966169852797	1385.47641307450
972.325964749230	1388.59563087441
965.302490493396	1385.07977832674
958.774456116715	1385.63363851896
951.700736139513	1389.15973097014
951.723116041675	1382.87960811503
945.005049508612	1376.57016973942
937.723477785087	1378.36022830346
931.468277816438	1380.20328535995
923.520177457719	1381.24829090188
923.468440200494	1387.14857325408
917.234096070951	1390.24501825771
909.557933099338	1393.58041646196
903.130645486550	1393.60003901443
895.986871658472	1395.16694597013
889.166864620724	1391.42160195927
881.631833239447	1392.92672170441
875.049612032251	1389.72316957465
867.427540314273	1393.69031472358
860.732283452133	1391.44404770828
853.051180799597	1395.70358899983

Here is my code:
poly2 = expandPolygon(poly, 15);
 figure;
plot(poly(:, 1),poly(:, 2), 'linewidth', 2);
hold on; plot(poly2{1}(:, 1),poly2{1}(:, 2), 'm')
axis equal;

**Comment by dlegland** [comment]
Hi,

the problem comes from the duplication of the first and last vertices of the polygon. When removing the last vertex for processing, you get a more relevant result:
`poly2 = expandPolygon(poly(1:end-1,:), 15);`

The same problem can occur when getting result of polygon processing algorithms, and not necessarily for first/last vertices. You can check the `removeDuplicateVertices` function that aims at cleaning up polygon for that purpose.

Best,
David

**Comment by JR9124** [comment]
Thanks for your help
