### ISSUE TITLE
intersectPlaneMesh for >2 faces per edge?

### ISSUE THREAD

**Issue by spacecraze** [mattools/matGeom#112]
Hey David! 

I'm not sure whether this is the place to post.. Forgive me if it isn't. 

Is there a way to cut a mesh that has edges with >2 faces? There is a mesh I wish to intersect with a plane that has 3 faces per edge in some areas, but is throwing errors because of that.

I have the vertex and face mat files if needed to recreate. 

Cheers!

Ben

**Comment by oqilipo** [comment]
I think that non-manifold edges are not supported. You might try to fix this before with ensureManifoldMesh.m

**Comment by dlegland** [comment]
Hi Ben,
as oqilipo stated, there is no support for meshes with edges connected to more than 2 faces. You need to cleanup / repair your mesh before computing intersection....
