### ISSUE TITLE
add new intersection functions for 3D line segments

### ISSUE THREAD

**Issue by dlegland** [mattools/matGeom#115]
- [x] intersection of 3D line segment with 3D polygon (can be based on intersectLinePolygon3d)
- [x] intersection of 3D line segment with 3D mesh  (can be based on intersectLineMesh3d)

**Comment by HagegeR** [comment]
I thought about making it possible to do multiple lines for one mesh

**Comment by dlegland** [comment]
ok, I'll have a look!

**Comment by dlegland** [comment]
Hi,
I've added new functions for intersection of 3D edge with either 3D polygon or 3D mesh!
The function intersectEdgePolygon3d can handle multiple polygons. The function intersectEdgeMesh3d is limited to only one edge at a time however.

**Comment by HagegeR** [comment]
ok, I can use that, but multiple lines can make my code a lot faster if it can really be vectorized

**Comment by dlegland** [comment]
I agree, but I need to change return type , so I have to check there no regression... I keep it open!

**Comment by svenholcombe** [comment]
Hi David, long time no see - I'll take a look at this too.

**Comment by HagegeR** [comment]
Thanks @svenholcombe and @dlegland for the great implementation and documentation!
