### ISSUE TITLE
drawEdge3d on app opens a new figure

### ISSUE THREAD

**Issue by HagegeR** [mattools/matGeom#119]
First I'm grateful for your effort in bringing such a great tool, it's so useful and well written!

I'm having a little issue with the drawEdges3D that I call from an app with axis as first input.

Because of this line:

https://github.com/mattools/matGeom/blob/9d0ae39cde4fafe32d46ea02fde15b0851450184/matGeom/geom3d/drawEdge3d.m#L72

And the call to parseDrawInput without axis as first input to it, it calls to gca wich then opens a figure because the current figure is an app and gca can't return that...

I tried to fix this manually but simply putting hAx as first input won't work because it makes the code behave completely differently when first input is axis and when it's not...

Do you think the refactoring can be done?
If it's to difficult I'll probably just close the figure after my call to drawEdge, but I wanted you to know.

**Comment by oqilipo** [comment]
hAx has to be an axes handle. Do you have an axes in your app?

**Comment by HagegeR** [comment]
yes, a uiaxis to be precise.

P.S.: I'm actually calling drawLine3d which calls to drawEdges3D from the app with the axis within the app as the first input, if it help..

**Comment by oqilipo** [comment]
I've pushed a fix https://github.com/mattools/matGeom/commit/a4c6c93c1fd9badb4c147c6a3d99eac6ae791f50 . 

Works for me with:
```
h1 = uiaxes;
h2 = uiaxes;
drawLine3d(h1, [0 0 0 1 1 1], 'Color','g')
```

**Comment by HagegeR** [comment]
works for me too, thanks :)
