### ISSUE TITLE
reversePlane

### ISSUE THREAD

**Issue by oqilipo** [mattools/matGeom#12]
Hi 

Am I right, that this function should change the direction of the plane normal?
If so, there is a bug.
```
plane = [0 0 0 1 0 0 0 1 0];

planeNormal(plane)

revPlane = reversePlane(plane);

planeNormal(revPlane)
```

results in:
```
reversePlane_test
ans =
     0     0     1
ans =
     0     0     1
```

Kind regards

**Comment by dlegland** [comment]
oops... you're totally right.
I'll fix it ASAP.

**Comment by dlegland** [comment]
fixed!
