### ISSUE TITLE
False results of intersectLinePolygon function for

### ISSUE THREAD

**Issue by bektasaykut** [mattools/matGeom#120]
```
line = [-2 -2 -1 -1];
poly = [0 0;10 0;10 10;0 10;0 0];
plot([line(1) line(3)], [line(2) line(4)],'-o');
hold on;
plot(poly(:,1),poly(:,2));
res = intersectLinePolygon(line, poly)
```
res =

     0     0
    10    10

result is [0 0] and [10 10].

Given line is a line segment. So it is limited betwen [-2 -2] and [-1 -1]

So result should be empty.

![fault intersections](https://user-images.githubusercontent.com/412625/111920236-e9fbef00-8a9e-11eb-9c86-188e6ba9f915.jpg)

**Comment by oqilipo** [comment]
You may convert the line to an edge and try intersectEdgePolygon ;-)

**Comment by dlegland** [comment]
yes, exactly!

The MatGeom library handles both "lines" and "edges":
* lines correspond to infinite lines, defined by an origin point and a direction
* edges correspond to the finite line segment bonded by two extremity points.

In this case, the use of edge is more appropriate.

**Comment by bektasaykut** [comment]
Thank you very much.
It did work.
