### ISSUE TITLE
intersectLineCircle fails with several lines and circles

### ISSUE THREAD

**Issue by kakila** [mattools/matGeom#122]
Hi,
the following bug was reported in the matgeom package in Octave:

> I am using GNU Octave with the package matgeom-1.2.2
>
> If I use the function “intersectLineCircle(lines,circles)” with multiple lines and circles I find an error message
> when in the array of lines one line has intersections with its corresponding circle and the subsequent line doesn’t.
> 
> e.g:
> 
> I use circles = [ 0 0 1 ; 0 0 1]
> and lines = [ 0 0 1 0; 2 2 1 0]
> 
> then I get the error:
> 
> error: reshape: can’t reshape 4x1 array to 2x2x2 array
> 
> Inspection of the function intersectLineCircle.m in the package gives me the information that the problem likely
> is in the conditional part:
> 
> if nCircles == 1
>     points = [...
>         line(1:2) + u(:,1) .* line(3:4); ...
>         line(1:2) + u(:,2) .* line(3:4)];
> else
>     tmp = [...
>         line(valid, 1:2) + u(:,1) .* line(valid, 3:4) ...
>         line(valid, 1:2) + u(:,2) .* line(valid, 3:4)].';
>         points(:, :, valid) = permute(reshape(tmp, [2, 2, nCircles]), [2 1 3]);
> end
> 
> And specifically in the “else” part.

I confirm that the following code fails with the mentioned error:

```
circles = [ 0 0 1 ; 0 0 1];
lines    = [ 0 0 1 0; 2 2 1 0];
intersectLineCircle (lines, circles)
```

**Comment by dlegland** [comment]
Hi,
thanks for reporting, I'll check this.

**Comment by dlegland** [comment]
ok, fixed in https://github.com/mattools/matGeom/commit/7c54eb3c2e81862ce735fdf8f65966873ffb7a46!
