### ISSUE TITLE
help text for SPH2CART2 and SPH2CART2D has incorrect input order and function name

### ISSUE THREAD

**Issue by NRJank** [mattools/matGeom#123]
As per  https://octave.discourse.group/t/error-in-sph2cart2d-function-help-in-package-matgeom-octave-6-1/724 
and https://savannah.gnu.org/bugs/?60032

1. the help text for SPH2CART2D says SPH2CART2 in the usage examples
2. both functions list the input order for separate inputs as (THETA, PHI, RHO), and the order for the single input as S = [phi theta rho].   however, it appears from the first nargin == 1 block that the code treats inputs as (THETA, PHI, RHO) for both separate and single inputs. The SPH2CART2 help text indicates that an order change was made in the code in 2006, but it seems the help text was never updated to match.

**Comment by dlegland** [comment]
Hi,
thanks for reporting!
I did not work on these functions for a while, maybe it's time to cleanup and check consistency of code and doc!
David

**Comment by dlegland** [comment]
fixed in https://github.com/mattools/matGeom/commit/973fe2f0680638ce226b78dbbfc0a080f4df1bc1
