### ISSUE TITLE
Documentation on how to cite the work

### ISSUE THREAD

**Issue by wspr** [mattools/matGeom#126]
We would like to cite this work in a publication but it's not clear from the Github site what your preferred way to do this would be. Could you please consider adding (say) a Zenodo DOI and/or publishing the work through an outlet such as [JOSS](https://joss.theoj.org) so the work can be acknowledged formally?

**Comment by oqilipo** [comment]
Yes, good idea. I can recommend Zenodo. It is really easy to create a DOI for an release of your repository. An DOI batch is provided that you can add to the README.md.

**Comment by dlegland** [comment]
hi,
yes, it would be good to provide better citation guidelines. I think I can manage a zenodo DOI in a near future. Will be opportunity for new release.
I was also envisioning a technical publication, and JOSS was also in the scope, but time is lacking...

**Comment by dlegland** [comment]
well, zenodo created (that was simpe indeed!):
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.5768193.svg)](https://doi.org/10.5281/zenodo.5768193)

**Comment by wspr** [comment]
Many thanks! Quick response much appreciated. How's this as a citation?

> David Legland et al. (2021) "MatGeom library for geometric computing with Matlab" DOI: 10.5281/zenodo.5768193

**Comment by dlegland** [comment]
yes, this citation is perfect for me!

**Comment by oqilipo** [comment]
I think this issue can be closed. The information was added to the README.md.
