### ISSUE TITLE
Octave install warning about verLessThan.m

### ISSUE THREAD

**Issue by justinkelly-ie** [mattools/matGeom#128]
Hi, I'm Getting the following warning when installing in Octave: 

warning: Permanently renaming verLessThan.m since it is already present

**Comment by dlegland** [comment]
Hi,

this is strange, as the file belongs to Matlab, but is not included into MatGeom...

maybe the problem comes from octave updates to match the function. Have you encoutered it with other libs?

**Comment by justinkelly-ie** [comment]
Hi, thanks for the reply. 

I could install the general package. 

I get a similar message attempting to install matgeom, full message:

warning: function /var/home/justin/.var/app/org.octave.Octave/data/octave/api-v57/packages/matgeom-1.2.3/verLessThan.m shadows a core library function
warning: called from
    doc_cache_create>gen_doc_cache_in_dir at line 146 column 5
    doc_cache_create at line 62 column 12
    install>generate_lookfor_cache at line 840 column 5
    install at line 241 column 7
    pkg at line 603 column 9

warning: Permanently renaming verLessThan.m since it is already present
warning: called from
    __matgeom_package_register__ at line 41 column 9
    /var/home/justin/.var/app/org.octave.Octave/data/octave/api-v57/packages/matgeom-1.2.3/PKG_ADD at line 2 column 1
    doc_cache_create>gen_doc_cache_in_dir at line 146 column 5
    doc_cache_create at line 62 column 12
    install>generate_lookfor_cache at line 840 column 5
    install at line 241 column 7
    pkg at line 603 column 9

I just updated to Octave 7 and now getting this error (on Fedora Silverblue):

pkg install -forge geometry
clipper.cpp: In function ‘void ClipperLib::InitEdge(ClipperLib::TEdge*, ClipperLib::TEdge*, ClipperLib::TEdge*, const ClipperLib::IntPoint&)’:
clipper.cpp:750:14: warning: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct ClipperLib::TEdge’; use assignment or value-initialization instead [-Wclass-memaccess]
  750 |   std::memset(e, 0, sizeof(TEdge));
      |   ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
clipper.cpp:95:8: note: ‘struct ClipperLib::TEdge’ declared here
   95 | struct TEdge {
      |        ^~~~~
In file included from /usr/include/c++/11.2.0/set:60,
                 from polygon.cpp:12:
/usr/include/c++/11.2.0/bits/stl_tree.h: In instantiation of ‘static const _Key& std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_S_key(std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Const_Link_type) [with _Key = {anonymous}::SweepEvent*; _Val = {anonymous}::SweepEvent*; _KeyOfValue = std::_Identity<{anonymous}::SweepEvent*>; _Compare = {anonymous}::SegmentComp; _Alloc = std::allocator<{anonymous}::SweepEvent*>; std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Const_Link_type = const std::_Rb_tree_node<{anonymous}::SweepEvent*>*]’:
/usr/include/c++/11.2.0/bits/stl_tree.h:2069:47:   required from ‘std::pair<std::_Rb_tree_node_base*, std::_Rb_tree_node_base*> std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_get_insert_unique_pos(const key_type&) [with _Key = {anonymous}::SweepEvent*; _Val = {anonymous}::SweepEvent*; _KeyOfValue = std::_Identity<{anonymous}::SweepEvent*>; _Compare = {anonymous}::SegmentComp; _Alloc = std::allocator<{anonymous}::SweepEvent*>; std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::key_type = {anonymous}::SweepEvent*]’
/usr/include/c++/11.2.0/bits/stl_tree.h:2122:4:   required from ‘std::pair<std::_Rb_tree_iterator<_Val>,bool> std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_insert_unique(_Arg&&) [with _Arg = {anonymous}::SweepEvent* const&; _Key = {anonymous}::SweepEvent*; _Val = {anonymous}::SweepEvent*; _KeyOfValue = std::_Identity<{anonymous}::SweepEvent*>; _Compare = {anonymous}::SegmentComp; _Alloc = std::allocator<{anonymous}::SweepEvent*>]’
/usr/include/c++/11.2.0/bits/stl_set.h:512:25:   required from ‘std::pair<typename std::_Rb_tree<_Key, _Key, std::_Identity<_Tp>, _Compare, typename __gnu_cxx::__alloc_traits<_Allocator>::rebind<_Key>::other>::const_iterator, bool> std::set<_Key, _Compare, _Alloc>::insert(const value_type&) [with _Key = {anonymous}::SweepEvent*; _Compare = {anonymous}::SegmentComp; _Alloc = std::allocator<{anonymous}::SweepEvent*>; typename std::_Rb_tree<_Key, _Key, std::_Identity<_Tp>, _Compare, typename __gnu_cxx::__alloc_traits<_Allocator>::rebind<_Key>::other>::const_iterator = std::_Rb_tree<{anonymous}::SweepEvent*, {anonymous}::SweepEvent*, std::_Identity<{anonymous}::SweepEvent*>, {anonymous}::SegmentComp, std::allocator<{anonymous}::SweepEvent*> >::const_iterator; typename __gnu_cxx::__alloc_traits<_Allocator>::rebind<_Key>::other = std::allocator<{anonymous}::SweepEvent*>; typename __gnu_cxx::__alloc_traits<_Allocator>::rebind<_Key> = __gnu_cxx::__alloc_traits<std::allocator<{anonymous}::SweepEvent*>, {anonymous}::SweepEvent*>::rebind<{anonymous}::SweepEvent*>; typename _Allocator::value_type = {anonymous}::SweepEvent*; std::set<_Key, _Compare,_Alloc>::value_type = {anonymous}::SweepEvent*]’
polygon.cpp:208:22:   required from here
/usr/include/c++/11.2.0/bits/stl_tree.h:770:15: error: static assertion failed: comparison object must be invocable as const
  770 |               is_invocable_v<const _Compare&, const _Key&, const _Key&>,
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/11.2.0/bits/stl_tree.h:770:15: note: ‘std::is_invocable_v<const {anonymous}::SegmentComp&, {anonymous}::SweepEvent* const&, {anonymous}::SweepEvent* const&>’ evaluates to false
make: *** [Makefile:15: polygon.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from /usr/include/c++/11.2.0/set:60,
                 from martinez.h:19,
                 from martinez.cpp:9:
/usr/include/c++/11.2.0/bits/stl_tree.h: In instantiation of ‘static const _Key& std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_S_key(std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Const_Link_type) [with _Key = Martinez::SweepEvent*; _Val = Martinez::SweepEvent*; _KeyOfValue = std::_Identity<Martinez::SweepEvent*>; _Compare = Martinez::SegmentComp; _Alloc = std::allocator<Martinez::SweepEvent*>; std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Const_Link_type = const std::_Rb_tree_node<Martinez::SweepEvent*>*]’:
/usr/include/c++/11.2.0/bits/stl_tree.h:2069:47:   required from ‘std::pair<std::_Rb_tree_node_base*, std::_Rb_tree_node_base*> std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_get_insert_unique_pos(const key_type&) [with _Key = Martinez::SweepEvent*; _Val = Martinez::SweepEvent*; _KeyOfValue = std::_Identity<Martinez::SweepEvent*>; _Compare = Martinez::SegmentComp; _Alloc = std::allocator<Martinez::SweepEvent*>; std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::key_type = Martinez::SweepEvent*]’
/usr/include/c++/11.2.0/bits/stl_tree.h:2122:4:   required from ‘std::pair<std::_Rb_tree_iterator<_Val>,bool> std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_insert_unique(_Arg&&) [with _Arg = Martinez::SweepEvent* const&; _Key = Martinez::SweepEvent*; _Val = Martinez::SweepEvent*; _KeyOfValue = std::_Identity<Martinez::SweepEvent*>; _Compare = Martinez::SegmentComp; _Alloc = std::allocator<Martinez::SweepEvent*>]’
/usr/include/c++/11.2.0/bits/stl_set.h:512:25:   required from ‘std::pair<typename std::_Rb_tree<_Key, _Key, std::_Identity<_Tp>, _Compare, typename __gnu_cxx::__alloc_traits<_Allocator>::rebind<_Key>::other>::const_iterator, bool> std::set<_Key, _Compare, _Alloc>::insert(const value_type&) [with _Key = Martinez::SweepEvent*; _Compare = Martinez::SegmentComp; _Alloc = std::allocator<Martinez::SweepEvent*>; typename std::_Rb_tree<_Key, _Key, std::_Identity<_Tp>, _Compare, typename __gnu_cxx::__alloc_traits<_Allocator>::rebind<_Key>::other>::const_iterator = std::_Rb_tree<Martinez::SweepEvent*, Martinez::SweepEvent*, std::_Identity<Martinez::SweepEvent*>, Martinez::SegmentComp, std::allocator<Martinez::SweepEvent*> >::const_iterator; typename __gnu_cxx::__alloc_traits<_Allocator>::rebind<_Key>::other = std::allocator<Martinez::SweepEvent*>; typename __gnu_cxx::__alloc_traits<_Allocator>::rebind<_Key> = __gnu_cxx::__alloc_traits<std::allocator<Martinez::SweepEvent*>, Martinez::SweepEvent*>::rebind<Martinez::SweepEvent*>; typename _Allocator::value_type = Martinez::SweepEvent*; std::set<_Key, _Compare, _Alloc>::value_type = Martinez::SweepEvent*]’
martinez.cpp:137:27:   required from here
/usr/include/c++/11.2.0/bits/stl_tree.h:770:15: error: static assertion failed: comparison object must be invocable as const
  770 |               is_invocable_v<const _Compare&, const _Key&, const _Key&>,
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/11.2.0/bits/stl_tree.h:770:15: note: ‘std::is_invocable_v<const Martinez::SegmentComp&,Martinez::SweepEvent* const&, Martinez::SweepEvent* const&>’ evaluates to false
make: *** [Makefile:15: martinez.o] Error 1
make: Entering directory '/tmp/oct-fG1v00/geometry-4.0.0/src'
/app/bin/mkoctfile-7.1.0 -Wall -mex -g clipper.cpp mexclipper.cpp
/app/bin/mkoctfile-7.1.0 -c connector.cpp -o connector.o
/app/bin/mkoctfile-7.1.0 -c martinez.cpp -o martinez.o
/app/bin/mkoctfile-7.1.0 -c polygon.cpp -o polygon.o
make: Leaving directory '/tmp/oct-fG1v00/geometry-4.0.0/src'

error: pkg: error running 'make' for the geometry package
error: called from
    configure_make at line 117 column 9
    install at line 202 column 7
    pkg at line 603 column 9

**Comment by dlegland** [comment]
wow...

not sure I can help a lot, but few things:
* last version of the library is 1.2.5, it seems you got an older one
* I'm really lost in the error messages you got... 
* where did you get the library from? I know there was a port to octave, but I do not maintain the octave version (just try to keep the Matlab version as much compatible with octave as possible...). I suggest asking to the maintainer of the octave port.

Hope this helps...

**Comment by justinkelly-ie** [comment]
Ah, cool, thanks. I got if from Octave forge https://octave.sourceforge.io/packages.php 
Maybe updates have stalled, thanks for taking a look.
