### ISSUE TITLE
distanceLines3d: Additional ouput: points on the line

### ISSUE THREAD

**Issue by oqilipo** [mattools/matGeom#13]
Hi 

IMO it would be a nice feature if the function "distanceLines3d" could provide the points on the lines with the minimal distance as additional output.

Kind regards

**Comment by dlegland** [comment]
Hi,

I agree, this would be nice!
I had a quick look, but this does not seem that straightforward...
I add the task on my TODO list!

regards

**Comment by oqilipo** [comment]
Here is some code. But it works only if the two line matrices have the same size in the first dimension
```
clearvars; close all

line1 = [0 -25 -50 0 0 1; 25 25 0 1 1 0.5];
line2 = [0 -50 0 1 0 0; -50 0 50 1 0 2];

a = dot(line1(:,4:6),line1(:,4:6),2);
b = dot(line1(:,4:6),line2(:,4:6),2);
e = dot(line2(:,4:6),line2(:,4:6),2);

den = a.*e-b.*b; % 0, if lines are parallel
r = line1(:,1:3)-line2(:,1:3);
c = dot(line1(:,4:6),r,2);
f = dot(line2(:,4:6),r,2);

s = (b.*f - c.*e)./den;
t = (a.*f - c.*b)./den;

pt1 = line1(:,1:3) + line1(:,4:6).*s;
pt2 = line2(:,1:3) + line2(:,4:6).*t;

figure
xlim([-100, 100]),ylim([-100, 100]),zlim([-100, 100])
hold on; grid on
xlabel x; ylabel y; zlabel z;
drawLine3d(line1,'b')
drawLine3d(line2,'r')
drawPoint3d(pt1);
drawPoint3d(pt2);
view(3)
axis equal

distanceLines3d(line1, line2)
distancePoints3d(pt1, pt2)

**Comment by dlegland** [comment]
thanks, 
I'll add it ASAP.

**Comment by dlegland** [comment]
Hi,
I have added a fix. You can use the following syntax:
[d, pt1, pt2] = distanceLines3d(line1, line2);

I think the code can be improved , but it seems to work.
regards,
David
