### ISSUE TITLE
Delete changelog.txt(s) ?

### ISSUE THREAD

**Issue by oqilipo** [mattools/matGeom#162]
Are the changelog.txt files in
- geom2d
- geom3d
- meshes3d
- polygons2d

still required or can they be deleted?
Or should they be merged into CHANGELOG.md?

**Comment by dlegland** [comment]
They can all be removed. Git now povides better tracking of changes!

**Comment by oqilipo** [comment]
Do you also want to have the CHANGELOG.md also be removed?

**Comment by oqilipo** [comment]
> Do you also want to have the CHANGELOG.md also be removed?

?

**Comment by dlegland** [comment]
hi,
sorry for delay;
yes, changelogs can be removed as well. 
best
