### ISSUE TITLE
Move data files to subfolder or data folder?

### ISSUE THREAD

**Issue by oqilipo** [mattools/matGeom#163]
One could move data files like:
- apple.ply
- cube.ply
- dodecahedron.obj
- dodecahedron.ply
- icosahedron.ply
- mushroom.off
- teapot.obj

into a subfolder "matGeom\matGeom\meshes3d\data" or data folder "matGeom\data\meshes3d" to separate them from the functions?

**Comment by dlegland** [comment]
I was thinking on such idea yesterday; however I am not sure this really adds clarity. I prefere to keep them as is for the moment.
