### ISSUE TITLE
clipPolygon3dHP is not fully implemented

### ISSUE THREAD

**Issue by dlegland** [mattools/matGeom#164]

**Comment by oqilipo** [comment]
There are still two todos in clipPolygon3dHP
* What is the output if the plane is same as polygon plane?
* Rename this function to 'clipPolygon3d'

![grafik](https://github.com/mattools/matGeom/assets/15254908/62cf3f1c-7f0b-42a6-9e76-9b5610c988e1)

**Comment by oqilipo** [comment]
Two questions remain:
    What should be the output if the plane is same as polygon plane?
    Should we rename this function to: clipPolygonByPlane3d? 

Maybe reopen till final decision?

**Comment by dlegland** [comment]
Yes, I agree.

my opinion about the two questions:

* if plane is the same as polygon plane, this should return the same polygon. If I had to start from scratch I would maybe rather throw an error. However, several functions in MatGeom return default values (like NaN or Inf) in similar cases. It seems preferable to be consistent with the existing.
* For renaming: yes, cleary more obvious!

best,
David

**Comment by oqilipo** [comment]
Sounds good! 

One more question.
Before processing the input polygon it is checked if all points are in a plane. What tolerance would you use here? At the moment it is. 1e-8. But maybe you use some other (default) tolerance in other functions?

Kind regards

**Comment by oqilipo** [comment]
> Sounds good!
> 
> One more question. Before processing the input polygon it is checked if all points are in a plane. What tolerance would you use here? At the moment it is. 1e-8. But maybe you use some other (default) tolerance in other functions?
> 
> Kind regards

I've changed it to 1e-14 now.

**Comment by dlegland** [comment]
Hi,

there is no absolute default for tolerance within the library. I often use 1e-8, but other functions use 1e-12. Value 1e-14 is fine as well for me.

The problem is that this often depends on the range of input data. I usually try to make the tests on normalized values, but there stille may be some uncoverd cases;
