### ISSUE TITLE
Missing polygons2d.m

### ISSUE THREAD

**Issue by oqilipo** [mattools/matGeom#183]
Hi David

Why was polygons2d deleted back in the days: 33c91e6f990b7fef4e91587491289f1a4294883f?

It is still mentioned in some functions for example: polygonCentroid.

And it might be helpful to check how polygons are defined (CW, CCW).

Kind regards

**Comment by dlegland** [comment]
Hi,
it is now "integrated" into the "Contents.m" of the "polygons2d" repository. In fact, using "help polygons2d" will display contents of Contents.m, and the help of "polygons2d.m" would never be displayed.
Also, as many conventions are similar for polygons and polylines, this made sense to merge the description.

**Comment by oqilipo** [comment]
Got it. 

But then "polygons2d" should be removed from the "See also" section of the header section, right?

**Comment by dlegland** [comment]
not necessarily; when using CLI help, the "polygons2d" appears as a clickable link. I find it rather useful to quickly have an organized summary of functions related to another function.

**Comment by oqilipo** [comment]
Ah, right. This works nice.
