### ISSUE TITLE
Matgeom -  verLessThan: package "matlab" is not installed

### ISSUE THREAD

**Issue by HartmutLASOS** [mattools/matGeom#189]
Hi.

I'm trying to use the matgeom package for drawing a 3d circle. Package was installed, however upon using it the error message
" verLessThan: package "matlab" is not installed " shows up. 
The function DrawCircle3d seems to check for a matlab or "matlab package" Version:
"if verLessThan('matlab', '7.8')
    ind = find(cellfun('isclass', varargin, 'char'), 1, 'first');
else"

Anyone know how to solve the issue?

Thanks for your help.

**Update**- Workaround does the job: Copied the function content to new file and deleted the "verlessthan"  if case

**Comment by dlegland** [comment]
hi,

I just tested with release 2023a and it works fine. I'll try with release 2023b next week.

this is a strange behaviour, as there is no deprecation warning in the current doc... Are you sure there is no conflict with another "verLessThan" function?

**Comment by HartmutLASOS** [comment]
> hi,
> 
> I just tested with release 2023a and it works fine. I'll try with release 2023b next week.
> 
> this is a strange behaviour, as there is no deprecation warning in the current doc... Are you sure there is no conflict with another "verLessThan" function?

I reinstalled it again and yes, there seems to be such a conflict. Upon installing there is a warning, which I've missed.
"warning: Permanently renaming verLessThan.m since it is already present"
There is another _verlessthan.m_ in the _miscellaneous_ folder. However, since I have no admin control over the programme folder, the workaround solution will do the job for now.

Thanks for your help.
