### ISSUE TITLE
Ideas for additional functions

### ISSUE THREAD

**Issue by oqilipo** [mattools/matGeom#19]
Only some ideas that came into my mind

geom3d - additional functions:
- plane2 = transformPlane3d(plane, trans)

meshes3d - additional functions:
- [meshAbove, meshInside, meshBelow] = cutMeshByPlane(mesh, plane)
I could provide a function for this one

What do you think?

Kind regards
oqilipo

**Comment by dlegland** [comment]
Hi,
yes, good ideas!
for the cutMeshByPlane,  I think I have a starting implementation somewhere. I'll check.
regards,
David

**Comment by oqilipo** [comment]
Me, too, I only would have to add some comments and parsing.
My function outputs the three mesh parts with the faces above, inside and below the plane.
My function does NOT provide a sharp cut with a calculation of new edges, which meight be more time consuming. That could be added as additional feature.

Kind regards
oqilipo

**Comment by dlegland** [comment]
Hi,
I tyhink we can close the issue, as this is now implemented!
I agree with you, computing new edges would be time consuming... this would however better correspond to a "clipping". It's on the TODO list for a while...
regards!

**Comment by dlegland** [comment]
Hi
just a comment: I've migrating the repository to a new "organization" called mattools, in order to make the library little bit more visible. The new adress will be: [https://github.com/mattools/matGeom](https://github.com/mattools/matGeom)   

Regards!
