### ISSUE TITLE
input order of angles of drawEllipse3d

### ISSUE THREAD

**Issue by oqilipo** [mattools/matGeom#31]
Hi David

For me it seems a little bit inconsistent (and it was quite confusing ;-) ) that drawEllipse3d uses the order:
THETA PHI PSI as input
while other functions like rotation3dToEulerAngles, drawEllipsoid, drawCuboid use:
PHI THETA PSI

Wouldn't it make more sense to use PHI THETA PSI as standard in all functions?
http://mathworld.wolfram.com/EulerAngles.html

Kind regards
oqilipo

**Comment by dlegland** [comment]
Hi oqilipo,

Yes, I use two conventions for 3D angles, and I agree this may be confusing... Some explanations:
* for "solid" objects, it is usually more natural to consider rotation of the main axis axis, and then to use "yaw-pitch-roll" analogy. Hence the Phi-Theta-Psi convention, corresponding to XYZ Euler angles.
* for flat objects (3D ellipses or discs), I found it more natural to consider rotation of the normal angle, and the rotation around the normal angle. This convention is used also in astronomy. So the rotation angles are different, and are more related to the ZYZ Euler angle convention.

I do not know if there is an "ideal" solution. It seems that many different conventions are used, making it difficult to make different packages work together. I finally choose two different systems, by considering that each one was adapted to a given case, and that they were easy to represent (at least for me...).

regards,
David

**Comment by oqilipo** [comment]
Is this documented somewhere? Maybe [angles3d.m](https://github.com/mattools/matGeom/blob/master/matGeom/geom3d/angles3d.m)?

Then we could close this issue after 7 years :wink:.

**Comment by dlegland** [comment]
yes, clearly this neesd to be updated! I plan ti update the manuel during summer, I'll add this topic!

**Comment by dlegland** [comment]
I have updated the file angles3d! see commit https://github.com/mattools/matGeom/commit/c59c8ab0b85a7764418be3f81db135dd785ec8fc. I also made some links from the drawXXX functions.
I will update manual as well, but if this is fine for you we can close.

**Comment by oqilipo** [comment]
Thank you
