### ISSUE TITLE
Version number in Contents.m of geom2d

### ISSUE THREAD

**Issue by fralik** [mattools/matGeom#42]
The current version in the file is 1.0 dated from 21-Mar-2011. However, FileExchange provides version with number 1.23.1. Seems like releases are not published on GitHub.

**Comment by dlegland** [comment]
Hi,

yes, there is no consistency between release number in GtHub, in files, and on the FEx. I have'nt found how to manage properly for the moment, but I will try to updates the help files for the future release.

David

**Comment by fralik** [comment]
Hi!
What should be considered as the latest release? The one on FEx?

**Comment by dlegland** [comment]
Hi,
If you want the very latest version, you can clone the repository. Otherwise the FEx version is the most recent.

**Comment by fralik** [comment]
Thanks!
