### ISSUE TITLE
intersectPlaneMesh for meshes with open edge

### ISSUE THREAD

**Issue by oqilipo** [mattools/matGeom#43]
Hi David

May it be possible to extend intersectPlaneMesh to meshes with open edges (outline edges) in the intersection plane:

I attached an example: [intersectPlaneMesh_example.zip](https://github.com/mattools/matGeom/files/1378287/intersectPlaneMesh_example.zip)

Kind regards

![grafik](https://user-images.githubusercontent.com/15254908/31482447-a97b4958-af28-11e7-86e8-fdcd7fc44c47.png)

**Comment by dlegland** [comment]
Hi,

yes, I think it is possible (I mean the algorithm can be extended to manage the case of open meshes. I'll investigate this.

**Comment by zfshmn** [comment]
Hi David,
Thanks for all of your work on the Geom3D toolbox. I was wondering if there has been any updates for allowing intersecting a plane with an open mesh? This feature would greatly help my analysis
Thank you!
Zach

**Comment by dlegland** [comment]
Hi,
unfortunately not... The problem is the iteration over edge/vertices of the intersection. I do not know for the moment how to start iteration from extremities. 
Still on the TODO list...

**Comment by zfshmn** [comment]
Thank you for the update. I'll keep tinkering with it too and look forward to future updates if you figure it out. 
PS for the requested functions list: I'm looking to intersect an open mesh with plane to then mirror the mesh across that plane and add in vertices & faces at the mirror plane
Thanks again!

**Comment by dlegland** [comment]
well, better later than never, I finally implemented management of mesh-plane intersection for open meshes (commit d2c03def40936e0615d9e60232cc8ff879225490)! The new syntax is as follow:

    [closedCurves, openCurves] = intersectPlaneMesh(Plane, vertices, faces);

It returns closed polygons in first output argument (as before), and open polylines in second output argument. That way the function does not break existing code.

Hope you will find it useful...

**Comment by oqilipo** [comment]
Great, thank you! I used it for a few test cases and it works fine.

However, I'm not quite sure if the output arguments are optimal. Often one will need something like:
```
if isempty(closedCurves)
    curve = openCurves;
else
    curve = closedCurves;
end
```

One could use a 'legacy' flag. I think that the way how they do it in MATLAB's build-in functions.
See https://www.mathworks.com/help/matlab/ref/double.unique.html for example.

Kind regards

**Comment by dlegland** [comment]
Good to know it works fine!

I agree about output arguments, I was also wondering about what was the best choice. 
It may also depend on usage; I usually focus on closed meshes, so closed polygons as first output better fits me!

Another option is to gather all curves (open and closed) in a single cell array, and additionnally provide a logical array the same size as the curve array indicating whether the curve is closed or open. This will be also consistent with previous syntax.

Something like this:

    [allCurves, closedFlag] = intersectPlaneMesh(plane, vertices, faces);
    drawPolygon3d(allCurves(closedFlag), 'r');
    drawPolyline3d(allCurves(~closedFlag), 'b');

Best,

**Comment by oqilipo** [comment]
> Something like this:
> 
> ```
> [allCurves, closedFlag] = intersectPlaneMesh(plane, vertices, faces);
> drawPolygon3d(allCurves(closedFlag), 'r');
> drawPolyline3d(allCurves(~closedFlag), 'b');
> ```

Sounds good!

**Comment by dlegland** [comment]
Just comitted the modification: b897628b62f5cec276a5e4070c15fa3ea21f5d0e

**Comment by oqilipo** [comment]
Works great. Thank you.

I've also added the function clipMeshByPlane.m
![grafik](https://github.com/mattools/matGeom/assets/15254908/e4a11e3e-53c6-4080-b243-b15a55c4534d)
