### ISSUE TITLE
clipMeshVertices and isolated vertices

### ISSUE THREAD

**Issue by oqilipo** [mattools/matGeom#51]
Hi David

Is it intended that the output of clipMeshVertices contains isolated (non indexed) vertices?

If not, trimMesh could be added before output. 

Kind regards
oqilipo

**Comment by oqilipo** [comment]
^^^^ push ;-)

**Comment by dlegland** [comment]
Hi!

Sorry for delay... 
The function was originally developped to serve as basis of a more general mesh clipping function (that was finally not written...). I personnally prefere to keep all vertices within the box, and leave the "trimming" operation to the user.
I can update the doc if necessary. Would that be fine?

David

**Comment by oqilipo** [comment]
I think that would be useful. I would not expect that it contains non-indexed vertices and it introduced a really hard to find bug in my code ;-)

Thanks

**Comment by dlegland** [comment]
ok, I will add an option to include or not the isolated vertices.

**Comment by oqilipo** [comment]
That's a good idea. I also can do it, if you are busy?

**Comment by dlegland** [comment]
Hi,
I was already coding it... I have just pushed it (forgot to pull modifs before, so took more time than expected...). I have added a test case as well. So, should work fine!

**Comment by oqilipo** [comment]
Thank you!
