### ISSUE TITLE
What to return if line, plane, ... is outside the limits of the current axes?

### ISSUE THREAD

**Issue by oqilipo** [mattools/matGeom#57]
IMO we should keep this consistent.

drawLine3d returns h=-1
drawPlane3d returns h=[]

kind regards

**Comment by dlegland** [comment]
yes, I totally agree. I check it.

**Comment by dlegland** [comment]
fixed in https://github.com/mattools/matGeom/commit/5128bdc8cca0e3797c24c2fe4e911f40304ef2b0
