### ISSUE TITLE
Bug in drawPoint when submitting a single point using the single argument format

### ISSUE THREAD

**Issue by teddyort** [mattools/matGeom#59]
The documentation gives as an example:
`drawPoint([10 10]);`

However this example fails with the error:

> Index exceeds matrix dimensions.
> 
> Error in drawPoint (line 63)
>     if ~isnumeric (varargin{2})

There seems to be faulty logic on line 61 where it is assumed two arguments will be given if the first is a vector, when the expected behavior is that a vector with size (1x2) would be treated just like any other (Nx2) matrix with columns [x, y]. I would perhaps add a check for this edgecase.

**Comment by dlegland** [comment]
hi,
thanks for reporting,
I have fixed it in commit #77b85bd44a6094caecc86a6653b0a6560e6e563c 

regards,
