### ISSUE TITLE
Use struct with patch properties as 2nd input for drawPlane3d

### ISSUE THREAD

**Issue by oqilipo** [mattools/matGeom#6]
I would like to use a struct with patch properties as 2nd input for drawPlane3d.

But with Matlab 2016a it doesn't seem to work,

Here is an example and the figure:

```
clearvars; close all

addpath(genpath('matGeom\matGeom\geom3d'))

% New figure
figure('Color','w')
axis equal; view(3)

% Plot a sphere
R=10;
C=50;
[X,Y,Z] = sphere;
[spherePatch.faces, spherePatch.vertices, ~]  = surf2patch(X*R+C,Y*R+C,Z*R+C);

% Define patch properties
patchProps.EdgeColor = 'k';
patchProps.FaceColor = [0.75 0.75 0.75];
patchProps.FaceAlpha = 0.75;

% Draw a sphere with patch properties
patch(spherePatch, patchProps);

% Create a plane
Plane = createPlane([C C C], [1 1 -1]);

% Draw the plane with default properties
drawPlane3d(Plane)

% Draw the plane with patch properties
drawPlane3d(Plane, patchProps)
```

![drawplane3d](https://cloud.githubusercontent.com/assets/15254908/18205688/977f1f5c-7123-11e6-8bd2-6aed44f72360.png)

Thanks in advance

**Comment by dlegland** [comment]
Hi,
there was indeed a strange behaviour I have not noticed yet. I have commited a bug fix, hope this will fit your needs!
David

**Comment by oqilipo** [comment]
Thanks a lot.

Works fine.
