### ISSUE TITLE
Speed up isCoplanar.m

### ISSUE THREAD

**Issue by bewantbe** [mattools/matGeom#67]
Regarding current coplanar test in [isCoplanar.m](https://github.com/mattools/matGeom/blob/9c9e24ce6ba02644070fb7ef19eac013b7dc57b0/matGeom/geom3d/isCoplanar.m#L64).
As discussed in GNU Octave [scatter3 performance regression](https://savannah.gnu.org/bugs/?55751), the coplanar test can be done by SVD:

```Octave
%allpoints = [x y z];
%NOTE: use bsxfun(@minus, ...) for old MATLAB or ancient Octave.
v = allpoints - mean(allpoints, 1);
sv = svd(v);
copl = sv(3) <= tolerance * sv(1);
```

The smallest singular value sv(3) has meaning of "standard deviation to the best fit plane". sv(1) and sv(2) is the spreading of the plane, i.e. plane size is roughly sv(1) x sv(2).

Time complexity of this SVD test is O(n), n = rows(allpoints) number of points involved in test. The `nchoosek` approach is probably O(n^4) in the worst case.

PS: in Octave, we need to partition the points into coplanar sets. So we choose `eig` for faster coplanar test, at the cost of accuracy.

**Comment by dlegland** [comment]
Hi,

thanks for the tip! The author of the original submission also updated his contirbution to use the "rank" function, itself based on svd...
I modified the "isCoplanar" function to use the svd function as suggested.

**Comment by bewantbe** [comment]
Nice to hear that. I forgot to point out that the original one is faster if the input is all random. But I guess this is probably a minor issue. I'm OK to close this issue.
