### ISSUE TITLE
use of delaunayTriangulation in nndist

### ISSUE THREAD

**Issue by kakila** [mattools/matGeom#70]
The function nndist uses delaunayTriangulation instead of just delaunay  [(1)](https://ch.mathworks.com/help/matlab/ref/delaunay.html)

nndist only requires the connectivity list and makes no use at all of any object property of the result (line 59 and later in nndist). This makes nndist pay the price of constructing the object without any reasons to do so. 

The object construction is avoided by replacing line 59 with

```octave
DT = delaunay (points);
```
and later uses of `DT.ConnectivityList` with just `DT`

**Comment by dlegland** [comment]
Hi,
thanks for the fix. I'll update nndist.

**Comment by dlegland** [comment]
fixed in d6b594603f49242b6029f16fd053b858dcd212ab
