### ISSUE TITLE
First line of documentation ending in period?

### ISSUE THREAD

**Issue by kakila** [mattools/matGeom#72]
The automatic documentation generator for the [Octave Forge website](https://octave.sourceforge.io/geometry/), looks for a period to decide that the first line of the documentation is over.
Many docstrings in matgeom do not have the first sentence ending on period.

Would it be ok to have those ending with a period? If yes, I will request the merge.

**Comment by dlegland** [comment]
Hi,
yes, it's ok for me to have a period at the end of the first line of documentation.
