### ISSUE TITLE
renaming clipPolygon to cropPolygon

### ISSUE THREAD

**Issue by kakila** [mattools/matGeom#82]
Hi all,

GNU Octave implements several interfaces to true polygon clipping[1] while clipPolygon in matgeom is just cropping with a box. Would you agree to rename clipPolygon to cropPolygon and help porting the clipper version (mex interface)[2] to matgeom (I can't test on matlab)?

[1]: https://octave.sourceforge.io/geometry/function/clipPolygon.html
[2]: https://octave.sourceforge.io/geometry/function/clipPolygon_clipper.html

**Comment by oqilipo** [comment]
Renaming of the function might be avoided by proper parsing.

If the size of the second input argument is 1x4, it is a box and can be converted to a polygon.
If the size of the second input argument is nx2, it is a polygon.

A different  possible name could be booleanOperationOnPolygons?

**Comment by kakila** [comment]
Hi,

The problem is name collision. When geometry loads matgeom, clipPolygon gets shadowed. So either matgeom/clipPolygon gets renamed, or we need to make matgeom/clipPolygon compatible with GNU Octave's

geometry/clipPolygon handles boxes transparently, without the need of considering a special case. It covers and does more then matgeom/clipPolygon.
Check the code here
https://sourceforge.net/p/octave/geometry/ci/default/tree/inst/clipPolygon.m

The function could be adapted to Matlab easily, and just document that mrf method is not implemented in matgeom. Clipper should be easy to port, or maybe it runs directly on matlab already (mex interface).

There is an unilateral solution, we can remove/rename matgeom/clipPolygon when it is installed in GNU Octave. I wouldn't like to do this, in favor of collaboration.

**Comment by dlegland** [comment]
Hi,
I understand the problem of name collision, arising from the dependencies of the octave version from two different libraries (matgeom + clipper).

I prefere to keep the original name as is, first to keep compatibility, and second to keep naming homogeneity with other functions. 
(by the way, the term "crop" seems rather strange to me in the context of geometry...).

The integration of the "clipper" library can be considered. However this does not seem a totally clean solution to me. This adds a dependency, and the integration of mex files also requires additional work and unittesting.
I can consider adding a file integrating clipper, but using a different name as suggested by oqilip. I would reserve the name "polygonBooleanOp" (which is IMHO closer to the actual functionality than just clipping).

It should also be possible to rename the octave version of clipPolygon?

**Comment by kakila** [comment]
There are several packages that depend on geometry/clipPolygon, because it is a full-fledged function. I think you understand that this is unlikely for matgeom/clipPolygon. 

So if there is no renaming on your side, we will just remove your function from the Octave installation. It is sad to come to these terms, but it seems there is no interest for collaboration on your side.

**Comment by dlegland** [comment]
Hi,

just want to clarify that this is not a lack of interest in collaboration. I gladily accept contributions and suggestions, and if I do not agree I propose compromises.
In that case, my feeling is that the issue was presented in a quite "forcing" way -> the project owner (ie me) is asked to accept a modification, otherwise he is taxed of not wanting to collaborate...
I think there could have been different ways to introduce the request.

**Comment by kakila** [comment]
Hi David,

I am sorry if you do not like the way, but time is precious. I tried to be as direct as possible. We have been discussing this over Octave, we do not see many other options as the ones I proposed (in my first msg). If you do not want dependencies and you do not want to rename (a likely marginal function... is my guess...I am not trying to offed here, just trying to asses reality)

I can try to go back once again to the maintainers of mapping and the other packages and see if they are ok with the renaming of the function (been there, but well...) 

Note that we also offer polybool wrapping clipPolygon... the latter uses your naming convention (I asked this here when we were implementing it) so it can be added to matgeom eventually.

**Comment by kakila** [comment]
BTW, I think you are using a very restrictive notion of polygon clipping (the case of a box, which is often refereed as cropping) e.g. https://en.wikipedia.org/wiki/Sutherland%E2%80%93Hodgman_algorithm
clipping is against any other polygon, not just boxes. So the matgeom::clipPolygon is actually the misnomer. UPDATE: of course, crop is also used in more general contexts :( https://www.bluemarblegeo.com/knowledgebase/global-mapper-21/Scripting_Reference/Cropping_Operations.htm?TocPath=Scripting%20Reference%7CShared%20Parameters%7C_____1

Also, geometry already offers `polybool` as a matlab compatible wrapper.

**Comment by kakila** [comment]
Oh, I see your difficulty, you are using "clip" everywhere to mean against a box and just intersection...ahhh...

**Comment by kakila** [comment]
Dear matgeomers!

After much much discussion we have decided to phagocitate the functionality of matgeom::clipPolygon inside [geometry::clipPolygon](https://sourceforge.net/p/octave/geometry/ci/default/tree/inst/clipPolygon.m) and shadow it at loading time. This means that Octave matgeom uses will enjoy the matgeom version, but geometry users will use the more versatile function.

Switching between one or the other accounts to

```octave
pkg load geometry # geometry's function will be used
pkg unload geometry # matgeom's function will be used
```
We hope that, in the eventual inclusion of this functionality into matgeom, matgeom devs will consider [the current geometry signature and behavior](https://sourceforge.net/p/octave/geometry/ci/default/tree/inst/clipPolygon.m) for its implementation. This is to avoid the effort to correct the geometry function.

It is expected that many of the clip* functions in matgeom will face the same shadowing in the future.
Please let us know if you think you have a better solution.

Thanks for the time and messages.

I am closing the issue
