### ISSUE TITLE
fillPolygon doesn't handle holes correctly

### ISSUE THREAD

**Issue by kakila** [mattools/matGeom#85]
Polygons with holes are not filled correctly,
The following was expected to fill the regions delimited by the red edges

```octave
pol = [
6.0000   3.6667
7.0000   4.0000
6.0000   5.0000
6.0000   6.0000
5.0000   6.0000
4.0000   7.0000
3.4000   6.0000
2.0000   6.0000
2.0000   3.6667
1.0000   2.0000
2.0000   2.3333
2.0000   2.0000
6.0000   2.0000
6.0000   3.6667
NaN      NaN
3.0000   3.8333
3.7000   5.0000
4.5000   5.0000
5.0000   4.5000
5.0000   3.8333
3.0000   3.1667
3.0000   3.8333
NaN      NaN
4.0000   3.0000
5.0000   3.3333
5.0000   3.0000
4.0000   3.0000
];
fillPolygon(pol, 'g')
drawPolygon(pol, 'r')
```
My suggestion is to add to matgeom the GNU Octave geometry function [`polygon2patch`](https://sourceforge.net/p/octave/geometry/ci/default/tree/inst/polygon2patch.m) that handles all cases correctly.
As far as I can see, it is just a matter to adapting it to matgeom's code-stlye and matlab syntax. It is likely that the matgeom name would be `polygon2Patch` base don what I see in other conversion functions.

**Comment by oqilipo** [comment]
Try:
```
pol = [6	7	6	6	5	4	3.4000	2	2	1	2	2	6	6	NaN	...
       3	3.7000	4.5000	5	5	3	3	NaN	4	5	5	4;
       3.6667	4	5	6	6	7	6	6	3.6667	2	2.3333	2	2	3.6667	NaN ...
   	   3.8333	5	5	4.5000	3.8333	3.1667	3.8333	NaN	3	3.3333	3	3]';
figure('color','w')
fillPolygon(pol, 'g')
drawPolygon(pol, 'r')
```
![grafik](https://github.com/mattools/matGeom/assets/15254908/c4a8699e-822b-4344-9de4-99156c977d78)

Or: 
```
oRectangle = [0 0;10 0;10 10;0 10];
iRectangle = flipud(0.5*oRectangle+1);
pol = {oRectangle, iRectangle};
figure('color','w')
fillPolygon(pol)
```
![grafik](https://github.com/mattools/matGeom/assets/15254908/c021f411-a419-4255-aa17-bbe9234a2a5e)
